/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import edu.curso.view.LoginBoundary;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LoginBoundary.launch(LoginBoundary.class, args);
    }
}
