/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // Plugin oficial do JavaFX
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.mariadb)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "edu.curso.App"
}

// Configuração do JavaFX
javafx {
    version = "21" // Ajustado para 21 para bater com o seu java.toolchain
    modules = listOf("javafx.controls", "javafx.fxml") // No Kotlin, usamos listOf()
}